### ISSUE TITLE
Training won't converge. 

### ISSUE THREAD

**Issue by yashkant** [xuchen-ethz/fast-snarf#1]
Hi @xuchen-ethz! 

Thanks so much for releasing the code! 

I quickly tested this using the command `python train.py subject=50002`, and found really great speed-up! 

But unfortunately, the loss did not converge to reasonable value. Do you have any idea on what could have gone wrong?

Appreciate your help!

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/17530895/207234719-3c0951cf-47a9-4cda-a5c3-e32d4e99b4e5.png">

**Comment by yashkant** [comment]
Thanks for the quick response! 

I recently switched to 32GB V100, and I had the old SNARF code working on a 16GB V100. 

I am planning to rerun the old SNARF code on the newer 32GB gpu to check if that works. 

Will keep you posted!

**Comment by xuchen-ethz** [comment]
Hi @yashkant 

When debugging for another issue I realized that there are two parts of the code that do no not belong to this version and they cause the convergence problem you experienced earlier. I was testing on a different branch so did not catch this problem.

Really sorry for the problem and for your time I might have wasted! Now things are fixed and the training should work normally with the updated code.

Best Regards,
Xu

**Comment by yashkant** [comment]
Thanks @xuchen-ethz, really appreciate the fix! 

The code works for me now! :)

**Comment by xuchen-ethz** [comment]
great to know! thanks for the feedback
