### ISSUE TITLE
Weird demo results

### ISSUE THREAD

**Issue by hangg7** [xuchen-ethz/fast-snarf#2]
Hi Xu,

Thanks for publishing your code!

I have run into some really weird results by following the demo instruction:

https://user-images.githubusercontent.com/10098306/211760013-007d69bb-454e-46c6-a296-40b3853e5c2e.mp4

Results are obtained by building from `environment.yml`. Tested on
```
CUDA-10.2
RTX 2080 Ti
Driver version 515.43.04
```

I am pretty sure something has went wrong. Could you please share your thought?

**Comment by xuchen-ethz** [comment]
Hi @hangg7, thank you for reporting this issue! 

There is indeed something wrong! I forget to remove one line of code for coordinate normalization (which is not for MLP-based shape models). I've just pushed a commit to fix this. Now everything should be good now. If not please let me know.

Very sorry for this problem!

**Comment by hangg7** [comment]
Thanks Xu! I will give it a try and let you know

**Comment by hangg7** [comment]
Confirm it's fixed!

**Comment by xuchen-ethz** [comment]
great, thanks for testing it!
